module.exports = {
	siteURL: process.env.URL || 'http://localhost:8080',
	siteName: "Qofai Tech Purposes Website such as blogging and more...",
	siteDescription: 'Set of tools and valuable posts for tech and non tech users.',
	siteImage: '/assets/images/site/default.jpg',
	lang: 'en',
	locale: 'en_us',
	authorName: 'Med Amine',
	authorURL: 'Med Amine',
	authorEmail: 'team.qofai@gmail.com',
	twitterSite: '@QofaiDev',
	twitterCreator: '@QofaiDev',
	address: {
		street: '',
		city: '',
		state: '',
		zip: '',
		phoneDisplay: '',
		phoneCall: '',
		email: 'team.qofai@gmail.com',
	},
}
